### PR TITLE
Reduce log noise

### PR DESCRIPTION
**Pull request by hjiebsco**

### CODE REVIEW

**Comment by MikeTaylor** [comment]
I'm not sure about this. It is certainly true that when running in a Kubernetes cluster, which runs maybe 15 Z-servers and pings every one of them every second, the logs get drowned in noise. But I think that misbehaviour is a feature of Kubernetes configuration rather than of the Z39.50 server, which is performing perfectly reasonable logging for a non-psychopathic deployment situation.

On the other hand, I do accept that it's practically more pleasant to have the out-of-the-box configuration behave nicely under Kubernetes.

I'd be interested in @ihardy's thoughts.

**Comment by ihardy** [comment]
Psychopathy or not, I'm not sure I have a way around it, so this change is OK with me. This is the CMD I've been using in our environments, afiak @hjiebsco's the only the second user but it does seem to indicate others will probably want to run it this way too.

**Comment by MikeTaylor** [comment]
Ok, thanks @ihardy, we'll do it.

But let the record show I'm not truly happy about it. This is a Docker file, and there is nothing about running under Docker that means the poor server is going to be constantly spammed with fake connections. That's a Kubernetes problem, which I think means the proper solution belongs in Kubernetes configuration.

But never mind, we'll do the pragmatic thing.

**Comment by hjiebsco** [comment]
@MikeTaylor, just want to mention that I am using AWS ECS not Kubernetes. Docker container health needs to checked regularly, whether it is from Kubernetes or ECS. So it is nice to have the session messages filtered out. :)

**Pull request merged**
